name: Compile

on:
  push:
    paths:
      - '*.c'
      - '*.h'
      - '.github/workflows/compile.yml'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang -DSHELL mali_user_buf.c mempool_utils.c mem_write.c -o mali_user_buf

      - name: Uplaod
        uses: actions/upload-artifact@v4
        with:
          name: CVE-2022-46395
          path: mali_user_buf
